import "server-only";
import { randomUUID } from "node:crypto";
import { query, queryOne } from "@/lib/db";
import { loadAllSpecs, normalizeSignature } from "@/lib/specs/loader";
import { makeFingerprint } from "@/lib/specs/fingerprint";
import { designAndPickFirst } from "@/lib/elevenlabs/voice-design";
import { createAgent } from "@/lib/elevenlabs/agents";
import { generateSoundEffect } from "@/lib/elevenlabs/sound-effects";
import { ttsToBuffer } from "@/lib/elevenlabs/tts";
import { keyFor, putObject } from "@/lib/r2";
import type { CharacterRecord, CharacterSpec, Subject, VisionResult } from "@/lib/specs/types";

/** Main entry point: turn a vision result into a playable character record. */
export async function resolveCharacter(
  userId: string,
  vision: VisionResult,
  imageR2Key: string,
): Promise<CharacterRecord> {
  const specs = await loadAllSpecs();

  // 1. PAIR branch
  if (vision.secondary) {
    const pair = await findPairSpec(
      normalizeSignature(vision.primary.category),
      normalizeSignature(vision.secondary.category),
    );
    if (pair) {
      const id = await insertPairInstance(userId, pair.id, imageR2Key);
      return {
        id,
        kind: "pairing",
        display_name: pair.slug,
        voice_id: pair.voice_id,
        agent_id: pair.agent_id,
        ambient_r2_key: null,
        greeting_text: pickGreeting(specs.pairings.get(pair.slug)?.greeting_templates ?? []),
        image_r2_key: imageR2Key,
      };
    }
  }

  // 2. LANDMARK branch
  if (vision.landmark_slug) {
    const lm = await queryOne<{
      id: string; slug: string; name: string; voice_id: string; agent_id: string; ambient_r2_key: string | null;
    }>(
      "SELECT id, slug, name, voice_id, agent_id, ambient_r2_key FROM landmarks WHERE slug = $1",
      [vision.landmark_slug],
    );
    if (lm) {
      return {
        id: lm.id,
        kind: "landmark",
        display_name: lm.name,
        voice_id: lm.voice_id,
        agent_id: lm.agent_id,
        ambient_r2_key: lm.ambient_r2_key,
        greeting_text: pickGreeting(specs.landmarks.get(lm.slug)?.greeting_templates ?? []),
        image_r2_key: imageR2Key,
      };
    }
  }

  // 3. MEMORY branch
  const fp = makeFingerprint(vision.primary);
  const existing = await queryOne<{
    id: string;
    voice_id: string;
    agent_id: string;
    ambient_r2_key: string | null;
    category: string;
    display_name: string | null;
  }>(
    "SELECT id, voice_id, agent_id, ambient_r2_key, category, display_name FROM objects WHERE user_id = $1 AND fingerprint = $2",
    [userId, fp],
  );
  if (existing) {
    await query("UPDATE objects SET last_seen_at = NOW() WHERE id = $1", [existing.id]);
    // Returning-visit greeting: reuse a warm re-encounter line. Ideally we'd
    // generate a fresh memory-aware line via Gemini Text, but that's a future
    // step — the agent session's conversation will cover that surface.
    const greeting =
      "You came back. The light moved while you were gone — did you notice?";
    return {
      id: existing.id,
      kind: "category",
      display_name: existing.display_name ?? titleCase(existing.category),
      voice_id: existing.voice_id,
      agent_id: existing.agent_id,
      ambient_r2_key: existing.ambient_r2_key,
      greeting_text: greeting,
      image_r2_key: imageR2Key,
    };
  }

  // 4. NEW OBJECT branch — build a spec specific to *this* photograph.
  //
  // The 12 hand-authored category specs at .kiro/specs/categories/ are tonal
  // references (they shape Gemini's prompt via the identity steering doc);
  // they are NOT looked up at runtime to voice this specific thing. Every
  // photographed object gets its own name, voice design prompt, greeting,
  // and ambient — generated by Gemini per photo.
  //
  // Landmarks (branch 2) and pair-unlocks (branch 1) stay hand-authored.
  const rawCategory = normalizeSignature(vision.primary.category);
  const categoryLabel = normalizeCategoryLabel(rawCategory); // for storage + analytics only

  const syntheticSpec = buildSyntheticSpec(vision, categoryLabel);
  const greeting = syntheticSpec.greeting_templates[0]!;
  const useAuthoredPreview = greeting.length >= 100;
  const { voice_id } = await designAndPickFirst({
    description: syntheticSpec.voice_profile.design_prompt,
    preview_text: useAuthoredPreview ? greeting : undefined,
    model_id: syntheticSpec.voice_profile.model_id,
    voice_name: `auris-${categoryLabel}-${fp.slice(0, 8)}`,
  });
  const { agent_id } = await createAgent(syntheticSpec, voice_id);
  const ambient = await generateSoundEffect({
    prompt: syntheticSpec.ambient_signature.prompt,
    duration_seconds: syntheticSpec.ambient_signature.duration_seconds,
  });
  const ambientKey = keyFor("ambients", `${categoryLabel}-${randomUUID()}.mp3`);
  await putObject(ambientKey, ambient, "audio/mpeg");
  const greetingBuf = await ttsToBuffer(voice_id, greeting);
  const greetingKey = keyFor("greetings", `${randomUUID()}.mp3`);
  await putObject(greetingKey, greetingBuf, "audio/mpeg");

  const row = await queryOne<{ id: string }>(
    `
    INSERT INTO objects (user_id, fingerprint, category, image_r2_key, voice_id, agent_id, ambient_r2_key, display_name)
    VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
    RETURNING id
    `,
    [
      userId,
      fp,
      categoryLabel,
      imageR2Key,
      voice_id,
      agent_id,
      ambientKey,
      syntheticSpec.display_name,
    ],
  );
  return {
    id: row!.id,
    kind: "category",
    display_name: syntheticSpec.display_name,
    voice_id,
    agent_id,
    ambient_r2_key: ambientKey,
    greeting_text: greeting,
    image_r2_key: greetingKey, // placeholder; handler uses greetingKey for audio
  };
}

/**
 * Build a CharacterSpec from Gemini's per-photo output.
 *
 * The 12 authored category specs are *not* used here at runtime — they informed
 * the vision prompt (via identity.md's tonal rules) but the spec we use to
 * drive Voice Design + Agent creation comes straight from the image. This is
 * what "anything photographable is a potential character" actually means —
 * each laptop, each plant, each mug is its own character.
 */
function buildSyntheticSpec(
  vision: VisionResult & { character?: { name: string; voice_design: string; greeting: string; ambient: string; traits: string[]; emotional_baseline: string } },
  categoryLabel: string,
): CharacterSpec {
  const char = vision.character;
  // Fallback (vision didn't return a rich character block — keeps the pipeline
  // working even when Gemini omits the extended fields).
  const design_prompt =
    char?.voice_design ??
    `Warm adult voice, unhurried, slightly whimsical register. Speaks as ${categoryLabel} in a photograph taken just now.`;
  const greeting =
    char?.greeting ?? (vision.description || "You found me. What did you want to say?");
  const ambient_prompt =
    char?.ambient ?? "quiet room tone, soft distant movement, gentle air";

  return {
    schema_version: 1,
    kind: "category",
    slug: `synthetic-${categoryLabel}-${Date.now().toString(36)}`,
    display_name: char?.name ?? titleCase(categoryLabel),
    archetype: `a ${categoryLabel} in a photograph`,
    voice_profile: {
      design_prompt: design_prompt.slice(0, 1000),
      model_id: "eleven_multilingual_ttv_v2",
    },
    personality: {
      traits: (char?.traits ?? ["observant", "warm", "specific"]).slice(0, 5),
      speaking_quirks: [],
      emotional_baseline: char?.emotional_baseline ?? "warm attention",
    },
    greeting_templates: [greeting],
    memory_style: "notices the specifics of this photograph",
    first_person_transforms: [],
    ambient_signature: {
      prompt: ambient_prompt,
      duration_seconds: 10,
    },
    forbidden_registers: [
      "cheeky",
      "breaking-character",
      "moralizing",
      "uncanny",
      "Wikipedia-recitation",
    ],
  };
}

/**
 * Normalize the raw category Gemini returned into a consistent string for
 * storage + analytics. We keep whatever Gemini said (including allowed
 * generics like "laptop") — no mapping to the 12 — so the memory table
 * reflects what the user actually photographed.
 */
function normalizeCategoryLabel(raw: string): string {
  const cleaned = raw.trim().toLowerCase().replace(/\s+/g, "-");
  return cleaned.length > 0 ? cleaned.slice(0, 50) : "thing";
}

function titleCase(s: string): string {
  return s
    .replace(/-/g, " ")
    .replace(/\b\w/g, (c) => c.toUpperCase());
}

async function findPairSpec(a: string, b: string): Promise<
  | { id: string; slug: string; voice_id: string; agent_id: string }
  | null
> {
  return (
    (await queryOne(
      "SELECT id, slug, voice_id, agent_id FROM pair_specs WHERE (signature_a = $1 AND signature_b = $2) OR (signature_a = $2 AND signature_b = $1)",
      [a, b],
    )) ?? null
  );
}

async function insertPairInstance(
  userId: string,
  pairSpecId: string,
  photoKey: string,
): Promise<string> {
  const row = await queryOne<{ id: string }>(
    `INSERT INTO pair_instances (user_id, pair_spec_id, photo_r2_key) VALUES ($1, $2, $3) RETURNING id`,
    [userId, pairSpecId, photoKey],
  );
  if (!row) throw new Error("pair instance insert failed");
  return row.id;
}

function pickGreeting(templates: string[]): string {
  if (!templates.length) return "Hello.";
  // Deterministic-per-day: same object + same day → same greeting, different day → likely different.
  const day = Math.floor(Date.now() / (1000 * 60 * 60 * 24));
  return templates[day % templates.length]!;
}

/** Convenience wrapper for categories that also need Subject context. */
export function _debug_newSubjectKey(s: Subject): string {
  return makeFingerprint(s);
}
